# Generated by Django 3.2.3 on 2021-05-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='game.lobby'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='game.game'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='game.instrument'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='game.player'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='tone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hits', to='game.tone'),
        ),
        migrations.AlterField(
            model_name='player',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game.instrument'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='game.lobby'),
        ),
    ]
