# Generated by Django 3.2.3 on 2021-05-28 06:25

from django.db import migrations, models
import game.utils


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210528_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_start',
            field=models.DateTimeField(default=game.utils.create_start_game_datetime),
        ),
    ]
