# Generated by Django 3.2.3 on 2021-05-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210529_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='player',
        ),
    ]
