# Generated by Django 3.2.3 on 2021-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_hit_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='tone',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.DeleteModel(
            name='Tone',
        ),
    ]
